=== sos-axelor/axelor-open-suite/axelor-bpm/src/main/resources/xsd/bpm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://axelor.com/xml/ns/bpm"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns:op="http://axelor.com/xml/ns/bpm"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
	vc:minVersion="1.1">



	<xs:complexType name="SubProcess">
		<xs:sequence>
			<xs:group ref="op:ProcessElements"></xs:group>
		</xs:sequence>
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="string"></xs:attribute>
		<xs:attribute name="cardinality" type="int"></xs:attribute>
		<xs:attribute name="collection" type="string"></xs:attribute>
	</xs:complexType>

	<xs:element name="object-processes" type="op:ObjectProcess"></xs:element>



	<xs:complexType name="Events">
		<xs:sequence>
			<xs:element name="event" type="op:Event"
				maxOccurs="unbounded" minOccurs="1">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Gateways">
		<xs:sequence>
			<xs:element name="gateway" type="op:Gateway"
				maxOccurs="unbounded" minOccurs="1">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Activity">
		<xs:sequence>
			<xs:element name="button" type="op:Button" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
			<xs:element name="dmn" type="op:Dmns" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="if" type="xs:string"></xs:attribute>
		<xs:attribute name="help" type="xs:string"></xs:attribute>
		<xs:attribute name="onEnable" type="xs:string"></xs:attribute>
		<xs:attribute name="target" type="xs:string"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string"></xs:attribute>
		<xs:attribute name="model" type="string"></xs:attribute>
		<xs:attribute name="form" type="string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Comments">
		<xs:sequence>
			<xs:element name="comment" type="op:Comment" minOccurs="1"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>




	<xs:complexType name="Models">
		<xs:sequence>
			<xs:element name="model" type="op:Model"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Step">
		<xs:attribute name="name" type="ID"></xs:attribute>
		<xs:attribute name="ref" type="xs:string"></xs:attribute>
		<xs:attribute name="target" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Button">
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Dmns">
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="decision" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Model">
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="path" type="xs:string"></xs:attribute>
		<xs:attribute name="start" type="xs:boolean"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Comment">
		<xs:sequence>
			<xs:element name="to" type="op:ToTarget" maxOccurs="unbounded" minOccurs="1"></xs:element>
			<xs:element name="help" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Gateway">
		<xs:sequence>
			<xs:element name="branch" type="op:Branch"
				maxOccurs="unbounded" minOccurs="1">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="Branch">
		<xs:attribute name="if" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="ID" use="required"></xs:attribute>
		<xs:attribute name="target" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>


	<xs:complexType name="Event">
		<xs:attribute name="name" type="ID"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
		<xs:attribute name="target" type="xs:string"></xs:attribute>
		<xs:attribute name="interruptible" type="xs:string"></xs:attribute>
		<xs:attribute name="trigger" type="xs:string"></xs:attribute>
		<xs:attribute name="family" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="start"></xs:enumeration>
					<xs:enumeration value="end"></xs:enumeration>
					<xs:enumeration value="intermediate"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type" type="string"></xs:attribute>
		<xs:attribute name="attachedTo" type="string"></xs:attribute>
		<xs:attribute name="interruptive" type="boolean"></xs:attribute>
		<xs:attribute name="onEnable" type="string"></xs:attribute>
	</xs:complexType>



	<xs:complexType name="ToTarget">
		<xs:attribute name="target" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>



	<xs:complexType name="ObjectProcess">
		<xs:sequence>
			<xs:element name="process" type="op:Process"
				maxOccurs="unbounded" minOccurs="1">
			</xs:element>
			<xs:element name="subprocess" type="op:SubProcess" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="Process">
		<xs:sequence>
			<xs:element name="models" type="op:Models" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:group ref="op:ProcessElements"></xs:group>
		</xs:sequence>
		<xs:attribute name="name" type="ID"></xs:attribute>
		<xs:attribute name="title" type="string"></xs:attribute>
	</xs:complexType>

	<xs:group name="ProcessElements">
    	<xs:sequence>
    		<xs:element name="events" type="op:Events" maxOccurs="1"
    			minOccurs="1">
    		</xs:element>
    		<xs:element name="gateways" type="op:Gateways" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="activities" type="op:Activities"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="comments" type="op:Comments" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    </xs:group>



	<xs:complexType name="Activities">
		<xs:sequence maxOccurs="unbounded" minOccurs="1">
			<xs:element name="activity" type="op:Activity" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== sos-axelor/axelor-open-suite/axelor-bpm/src/main/resources/xsd/bpm-opportunity.xml
<?xml version="1.0" encoding="UTF-8"?>
<object-processes xmlns="http://axelor.com/xml/ns/bpm"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://axelor.com/xml/ns/bpm bpm.xsd ">
  <process name="mainOpportunityProcess" title="Main opportunity process">
    <models>
      <model name="com.axelor.apps.crm.db.Opportunity" start="true"/>
    </models>
    <events>
      <event name="startOfTheProcess" title="Start of the opportunity process" family="start"
        target="toNewGateway"/>
      <event name="endOfOpportunityProcess" family="end"/>
    </events>

    <gateways>
      <gateway name="toNewGateway" type="unique">
        <branch name="toNewBranch" target="createOpportunity"/>
      </gateway>
      
      <gateway name="toQualifyGateway" type="unique">
        <branch name="totoQualifyBranch" target="qualifyTheOpportunity"/>
      </gateway>
      
    </gateways>

    <activities>
      <activity type="user" name="createOpportunity" title="Create the opportunity"
        target="toQualifyGateway">
        <button name="next-stageBtn"/>
      </activity>
      
      <activity type="user" name="qualifyTheOpportunity" title="Qualify the opportunity"
        target="endOfOpportunityProcess">
        <button name="next-stageBtn-qaulify"/>
        <button name="previous-stageBtn-qaulify"/>
      </activity>

    </activities>

  </process>

</object-processes>

=== sos-axelor/axelor-open-suite/axelor-bpm/src/main/resources/xsd/bpm-opportunity2.xml
<?xml version="1.0" encoding="UTF-8"?>
<object-processes xmlns="http://axelor.com/xml/ns/bpm"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://axelor.com/xml/ns/bpm bpm.xsd ">
  <process name="mainOpportunityProcess" title="Main opportunity process">
    <models>
      <model name="com.axelor.apps.crm.db.Opportunity" start="true"/>
    </models>
    <events>
      <event name="startOfTheProcess" title="Start of the opportunity process" family="start"
        target="toNewGateway"/>
      <event name="previousFromNegotiation"
        title="Click on previous Button during negotiation" family="intermediate"
        target="toPropositionGateway" interruptive="true" trigger="eval: previous-stageBtn = true"/>
      <event name="archiveRecord" title="Archive the opportunity" family="intermediate"
        target="endOfOpportunityProcess" trigger="eval: isArchived = true"/>
      <event name="endOfOpportunityProcess" family="end"/>
      <event name="previousFromFinalState" family="intermediate" trigger="condition"
        onEnable="action-attrs-attributes"/>
    </events>

    <gateways>
      <gateway name="toNewGateway" type="unique">
        <branch name="toNewBranch" target="createOpportunity"/>
      </gateway>

      <gateway name="toQualifyGateway" type="unique">
        <branch name="totoQualifyBranch" target="qualifyTheOpportunity"/>
      </gateway>

      <gateway name="toPropositionGateway" type="unique">
        <branch if="previous-stageBtn" name="backToNewBranch" target="toNewGateway"/>
        <branch if="next-stageBtn" name="toMakePropositionBranch"
          target="makePropositionOpportunity"/>
      </gateway>

      <gateway name="toNegotiationGateway">
        <branch name="toQualifyGatewayBranch" target="toQualifyGateway"/>
        <branch name="toNegotiationBranch" target="negotiationGateway"/>
      </gateway>

      <gateway name="negotiationGateway" title="Negotiation" type="event">
        <branch name="negotiationPrevious" target="previousFromNegotiation"/>
        <branch name="archive" target="archiveRecord"/>
      </gateway>
    </gateways>

    <activities>
      <activity type="user" name="createOpportunity" title="Create the opportunity"
        target="toQualifyGateway">
        <button name="next-stageBtn"/>
      </activity>

      <activity type="user" name="qualifyTheOpportunity" title="Qualify the opportunity"
        target="toPropositionGateway">
        <button name="next-stageBtn-qaulify"/>
        <button name="previous-stageBtn-qaulify"/>
      </activity>

      <activity type="user" name="makePropositionOpportunity" title="Make a proposition"
        target="toNegotiationGateway">
        <button name="next-stageBtn-proposition"/>
        <button name="previous-stageBtn-proposition"/>
      </activity>

      <activity type="script" name="incrStatus" title="Increase Status" help="sdfsdfsfd"
        onEnable="action-attrs-1"/>

      <activity type="script" name="decrStatus" title="Decrease Status"
        onEnable="action-attrs-2"/>
    </activities>

    <comments>
      <comment name="comment1">
        <to target="activity1"/>
        <to target="activity2"/>
        <help>
          sdqfsqfdqsfdqsdfqsfdqfd
        </help>
      </comment>
    </comments>
  </process>

  <subprocess name="lostOpportunitySubProcess"
    title="Lost Opportunity  event sub process" type="subprocess type">
    <events>
      <event name="startOfTheLostSubProcess" title="Start of the lost sub process"
        family="start" target="lostReasonView" trigger="eval: closed-lostBtn"/>
      <event name="previousFromFinalState1" title="Click on previous Button when lost"
        family="intermediate" target="endOfOpportunityProcess"/>
      <event name="endOfOpportunityProcess1" family="end"/>
    </events>

    <activities>
      <activity type="script" name="lostReasonView" title="Open Lost reason popup"
        target="lostReason" onEnable="action-opportunity-view-opportunity-lost-popup-view"/>

      <activity type="user" name="lostReason" title="Indicate lost reason"
        if="eval: lostReason != null" model="Opportunity" form="opportunity-form-lost-popup"
        target="lostStatus" onEnable="action-attrs-3"/>

      <activity type="script" name="lostStatus" title="Change status to lost"
        target="previousFromFinalState"
        onEnable="action-attrs-4,action-opportunity-method-cancel-saleorders"/>
    </activities>
  </subprocess>

  <subprocess name="wonOpportunitySubProcess" title="Won Opportunity event sub process">
    <events>
      <event name="startOfTheWonSubProcess" title="Start of the won sub process"
        family="start" target="wonStatus" trigger="eval: closed-wonBtn"/>
      <event name="previousFromFinalState2" title="Click on previous Button when won"
        family="intermediate" target="endOfOpportunityProcess"/>
      <event name="endOfOpportunityProcess2" family="end"/>
    </events>

    <activities>
      <activity type="script" name="wonStatus" title="Change status to won"
        target="previousFromFinalState" onEnable="action-attrs-5"/>
    </activities>
  </subprocess>

  <subprocess name="scheduleEventSubProcess" title="Schedule event" type="...">
    <events>
      <event name="startOfTheScheduleSubProcess" title="Click on schedule event item"
        family="start" interruptive="false" target="endOfScheduleEventSubProcess"
        trigger="eval: scheduleEventItem"/>
    </events>
  </subprocess>

  <subprocess name="createQuotationSubProcess" title="Create a quotation">
    <events>
      <event name="newQuotation" title="New quotation" family="start" type="conditionnal"
        interruptive="false" trigger="eval: btn" target="createQuotationSubProcessSub1"/>
      <event name="end" family="end"/>
    </events>
  </subprocess>

  <subprocess name="createQuotationSubProcessSub1">
    <events>
      <event name="startSub" family="start" target="eventGateway"/>
      <event name="endSub" family="end"/>
      <event name="cancelEnd" family="end" type="cancel"/>
      <event name="partner" family="intermediate" type="conditionnal" trigger="eval: partner"
        target="custCreatedScript"/>
      <event name="notPartnerLead" family="intermediate" type="conditionnal"
        trigger="eval: !partner &amp;&amp; lead" target="clickOkOrCancel"/>
      <event name="notPartnerNotLead" family="intermediate" type="conditionnal"
        trigger="eval: !partner &amp;&amp; !lead" target="cancelEnd"/>
      <event name="triggerCreateCustProcess" family="intermediate" type="message"
        target="custCreated"/>
      <event name="custCreated" family="intermediate" type="message"
        target="custCreatedScript"/>
    </events>

    <gateways>
      <gateway name="eventGateway" type="event">
        <branch name="partnerBranch" target="partner"/>
        <branch name="notPartnerLeadBranch" target="notPartnerLead"/>
        <branch name="notPartnerNotLeadBranch" target="notPartnerNotLead"/>
      </gateway>
      <gateway name="uniqueGateway" type="unique">
        <branch if="ok" name="okBranch" target="triggerCreateCustProcess"/>
        <branch if="cancel" name="cancelBranch" target="cancelEnd"/>
      </gateway>
    </gateways>

    <activities>
      <activity type="user" name="clickOkOrCancel" title="Click on ok or cancel"
        target="uniqueGateway"/>
      <activity type="script" name="custCreatedScript"
        onEnable="action-sale-method-generate-sale-order" target="end"/>
    </activities>

  </subprocess>
</object-processes>
